V3/controllers harvest auth
WebCuratorTool/webcurator-webapp pull request #9
Opened 2019-11-27 06:12 UTC by leefrank9527

1. Fixed validation error presentation page: replaced Spring Tags with customized error parameters.
2. Fixed controllers:
  1) TabbedController: extracted a method to do initBind, binding and validation.
  2) Controllers of Harvest Authorisations, all controllers in package: org.webcurator.ui.site.controller.
  3) Fixed issues of target related controllers to match changed TabbedController.
  4) Commented useless mapping lines in ServletConfig.

2019-11-27 12:49 UTC, hannakoppelaar approved these changes
I think this is okay. @obrienben The related PR for core is yet to be reviewed by you. I guess they should be merged at the same time, since the changes in webapp depend on those in core. If you're happy with the PR for core, I'm fine with you merging both PRs to their respective master branches.

2019-12-02 08:37 UTC, obrienben requested changes
@leefrank9527 two buttons that I noticed didn't work. Did you want to fix and include them in this PR?

Transferring a permission
![image](https://user-images.githubusercontent.com/5760612/69944017-207cc600-154b-11ea-8198-e0ef8e7e4e3c.png)

![image](https://user-images.githubusercontent.com/5760612/69943930-e7dcec80-154a-11ea-877a-86ece7854695.png)

And generating letter/email
![image](https://user-images.githubusercontent.com/5760612/69944184-8ff2b580-154b-11ea-871b-dc4bfbdeb7d5.png)
![image](https://user-images.githubusercontent.com/5760612/69944214-a39e1c00-154b-11ea-934b-d9933261ecfc.png)

2019-12-02 08:37 UTC, obrienben commented on src/main/java/org/webcurator/ui/site/controller/SiteController.java
> +@RequestMapping("/curator/site/site.html")
Can you compare this line with some of the other controllers we have converted, I think we were dropping the ".html" from the end of the request mapping path.

2019-12-02 08:37 UTC, obrienben commented on src/main/java/org/webcurator/ui/site/controller/SitePermissionController.java
> +     * @param comm          The Spring command object.
Doesn't match the new name of the parameter - should now be 'command'.
Probably not worthy of a commit.

2019-12-02 08:37 UTC, obrienben commented on src/main/java/org/webcurator/ui/site/controller/SiteSearchController.java
> +@RequestMapping("/curator/site/search.html")
See previous comment about dropping the ".html" from request mapping path

2019-12-02 08:37 UTC, obrienben commented on src/main/java/org/webcurator/ui/target/controller/TabbedTargetInstanceController.java
> +@RequestMapping("/curator/target/target-instance.html")
Same comment about the ".html"

2019-12-02 08:37 UTC, obrienben commented on src/main/java/org/webcurator/ui/target/controller/TargetController.java
>  @RequestMapping("/curator/target/target.html")
Same comment about the ".html"

2019-12-03 22:14 UTC, leefrank9527 commented on src/main/java/org/webcurator/ui/site/controller/SitePermissionController.java
> +     * @param comm          The Spring command object.
Accepted. Changed the param in comments to match the actual parameter in the function.

2019-12-05 01:01 UTC, obrienben commented
@leefrank9527 anything else to include in this PR or is it done?

2019-12-05 05:23 UTC, frank-dia commented
@obrienben It's done.

2019-12-05 05:24 UTC, frank-dia commented
@obrienben It's done.

2019-12-05 19:56 UTC, merged